###################################################
# Makefile for the QCE8094 linux PHY driver
###################################################
ccflags-y += -Werror -Wall
TARGET := qce1204-phy
obj-m += $(TARGET).o
$(TARGET)-objs := qce1204.o
